### ISSUE TITLE
Mejora RDS

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo_-campo#2]
[mejora DRS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo_-campo/files/14315584/mejora.DRS.pdf)

**Comment by yanet02** [comment]
**CALIFICADO DE ACUERDO A LA RÚBRICA**

Portada = 25
Procedimiento = 22 
Figuras, ilustraciones y fotografías = 22
Resultados y conclusiones = 25

_Total = 94/100_
**CALIFICACIÓN =18.8**

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
